[[METIS]]
arch = "i686"
git-tree-sha1 = "ff107655135acd508fc7ef493950f3edfd59cd60"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "6c053592e32f58359892991dcbc0c1c34212ba50df30b8281cc3a31a7f35611d"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+2/METIS.v5.1.0.i686-linux-musl.tar.gz"
[[METIS]]
arch = "aarch64"
git-tree-sha1 = "d425991c3d00999ba7899f606383eca7190f2743"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "34250c471a99bc6ba1991bb15fbcbe98ac8751e0b7ad9619d61d6667e31f6f05"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+2/METIS.v5.1.0.aarch64-linux-musl.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "eea4f7604514c3f5ee94f46e7971de30cd09c5e0"
os = "windows"

    [[METIS.download]]
    sha256 = "03580c6a1a99e584d36d32f2145305791e5db536e5bbfd668bbe29fba9ef8532"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+2/METIS.v5.1.0.i686-w64-mingw32.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "8be50ff9253cd366fbd916357bbb928a55b50245"
os = "windows"

    [[METIS.download]]
    sha256 = "696b47ef92cae9593317a4d5ff56850dc4b91bc88a7ea5714dba382c5e896df2"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+2/METIS.v5.1.0.x86_64-w64-mingw32.tar.gz"
[[METIS]]
arch = "armv7l"
git-tree-sha1 = "15cf49d2b7b6d4fcdd7eb49b36e570fa4ee6d571"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "ea6ebe245211167cd3e1b49a5e9a9208d9fbabf3f6554a6394cdbd02b8a958b0"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+2/METIS.v5.1.0.armv7l-linux-gnueabihf.tar.gz"
[[METIS]]
arch = "armv7l"
git-tree-sha1 = "bcf7d061b2aa0132ad7de8a9b19d9e8921ecc6a6"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "ea8bf5dc28ffdc09ab3c0311b11140f88fbb40aa12ad32fb4e84200258f85ded"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+2/METIS.v5.1.0.armv7l-linux-musleabihf.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "4d3c30a1fa46f4ec7086958b9243b800c7bf4377"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "e3b7c3bf90a6f937aa38057811823c261693f2637b13d805655bff10980bd984"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+2/METIS.v5.1.0.i686-linux-gnu.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "ca3971ac481aa5e828144667f7279a9dba0c2e71"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "95caa78ee69cf3010575f1c0faa44bc8198bbfc4d98dd8896afcf81bdc811bb3"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+2/METIS.v5.1.0.x86_64-linux-gnu.tar.gz"
[[METIS]]
arch = "powerpc64le"
git-tree-sha1 = "142362df0e1dcc7532b710dc16b8eb7669fe938a"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "98ef09c65a60e52d5faed43a899e8be0572dc968514257b0656ebea7b1103158"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+2/METIS.v5.1.0.powerpc64le-linux-gnu.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "58788dd2feca6423ef4f380ef99183d396a18952"
os = "macos"

    [[METIS.download]]
    sha256 = "149a3ddecf8dea1635509baac6d9bf7566f23b97f300f83f7923f1a5dd80a7fa"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+2/METIS.v5.1.0.x86_64-apple-darwin14.tar.gz"
[[METIS]]
arch = "aarch64"
git-tree-sha1 = "a86f93304d054a15a22c6b85151ad60adb0fd381"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "3c86f9d635b8c6c838211c5c2d38cd1982f9010e825d9f96e54b83ba2e0ca4b2"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+2/METIS.v5.1.0.aarch64-linux-gnu.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "8f90b1666b65dc1afdd1b13a871e31d663ae02fd"
os = "freebsd"

    [[METIS.download]]
    sha256 = "f8bfa689c5858bdc9d84c0949edea726253c2cc33ef3f8c0de8e5b0b2bd1c499"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+2/METIS.v5.1.0.x86_64-unknown-freebsd11.1.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "83d6b21499e2aca4f1f441a79b145252b4b77876"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "74adcc2e55d62d50593e7495d02e9fb55e9e0e601e37dcdce9d82fb12857d468"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+2/METIS.v5.1.0.x86_64-linux-musl.tar.gz"
