[[METIS]]
arch = "aarch64"
git-tree-sha1 = "eb3330e5d596d737f017f4ea1d848b516c6274a2"
os = "macos"

    [[METIS.download]]
    sha256 = "241091172ab02a48411750bca62ff03a4cddcb13768ff32630b63c631aba95bf"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+1/METIS.v5.1.2.aarch64-apple-darwin.tar.gz"
[[METIS]]
arch = "aarch64"
git-tree-sha1 = "69543b1631f7871bd06e2b3ababfdb7617dec879"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "2d82f2e0e4d013eefe948b38d829e1ddb02adbaaa0cfd40ad451e09dc1595b15"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+1/METIS.v5.1.2.aarch64-linux-gnu.tar.gz"
[[METIS]]
arch = "aarch64"
git-tree-sha1 = "0e95b8ceef5462d437d044e04d506943db65e84a"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "331c88604ef753e4a0e4a605b77587a99d1439651d26098b92156c2fb16d7bb7"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+1/METIS.v5.1.2.aarch64-linux-musl.tar.gz"
[[METIS]]
arch = "aarch64"
git-tree-sha1 = "e997e496abb8b0b63e3b94dea9db1e71ed9ba700"
os = "freebsd"

    [[METIS.download]]
    sha256 = "923374e811f4e4034a84130e81055e8b4f555fb8080c9ee12b15eb0bb9ca5885"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+1/METIS.v5.1.2.aarch64-unknown-freebsd.tar.gz"
[[METIS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b1f69630031ab055dd64e9a32c1abb0fc3fb6cd9"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "84ba703b6c72cc3055ea839cbadc602fd3d0961c1826b571388f4213cbbda009"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+1/METIS.v5.1.2.armv6l-linux-gnueabihf.tar.gz"
[[METIS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d0abb8294b56092697ac4bb68d02ea5c7c4242c3"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "5714f83cf96ba1a1cde74e1fd18ac3ebc057232a7268c15718531c2d421476d4"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+1/METIS.v5.1.2.armv6l-linux-musleabihf.tar.gz"
[[METIS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cfaf0bab2e463319736afc075a5e60053c2e8bb7"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "fc9ea3046436e32cf67c0d17fbc5d7383d048aea51bbb6ea4b1bd0e5f9e14f6a"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+1/METIS.v5.1.2.armv7l-linux-gnueabihf.tar.gz"
[[METIS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f5069f6768b469299894088599f5fe0487910fad"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "b04eb1c2e5cae294845ebb018cd39cc149992860c6b3bfa04ac086dcf8c18050"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+1/METIS.v5.1.2.armv7l-linux-musleabihf.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "79ae8c2d6bd7af8b2835bebab028f37447d7eb72"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "d49a950589682eaba21e821dc95de2adf49956ccdce4bbe3b2a149d80982fd8e"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+1/METIS.v5.1.2.i686-linux-gnu.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "9f7577e4d08f1c6cbfabe10ead18cce5a2a0444f"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "64fde69baa28086831630cf7443f3ea3d7a49edbe9a5da10c4f3d4d7f29fbabc"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+1/METIS.v5.1.2.i686-linux-musl.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "0baec9331cab6b2c5c4398e927f5776aa520533b"
os = "windows"

    [[METIS.download]]
    sha256 = "72ce866406bd30dbc8ec143770bbc7a518053e52fb3585bdd5d9bee7dca88cd5"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+1/METIS.v5.1.2.i686-w64-mingw32.tar.gz"
[[METIS]]
arch = "powerpc64le"
git-tree-sha1 = "2292868e421c7e0070d1dc0dd134fb46e2c73a86"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "04763aad675c567803f84e82611d19c1f77c359e24b2d512a30ddc200b2b8676"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+1/METIS.v5.1.2.powerpc64le-linux-gnu.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "b03c687089c4bb6d2acae34588c70250bea8f51e"
os = "macos"

    [[METIS.download]]
    sha256 = "45e30b4bcac89d7c02b67550878af50e0c59a1d7a636ec5d77629d87e3b8f3a9"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+1/METIS.v5.1.2.x86_64-apple-darwin.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "4bf84065244972141c7d0af9249cb8b1a1b5f00b"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "442a91cc9b675e2a052471c33607f3af6c9a4915686e6b47d84ab1e295b01bd7"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+1/METIS.v5.1.2.x86_64-linux-gnu.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "8364ab30a8e4fd0fe33410cbc5d0a9941638da30"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "ecba80bcc5bda27c390eb7421a91b8c92c13093d8366292f3cfdc2dfff970f32"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+1/METIS.v5.1.2.x86_64-linux-musl.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "b61ef18888aa75e368b48e9af755a879093ccd82"
os = "freebsd"

    [[METIS.download]]
    sha256 = "40905b8716ff145799f3e0868e0b9ec4b7d824ad4bab6a09ba587e5ca579418d"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+1/METIS.v5.1.2.x86_64-unknown-freebsd.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "4d21c836e693a1156c23abb5b690cc898b2bf325"
os = "windows"

    [[METIS.download]]
    sha256 = "0b015680a46f255f8985501d7d4f3397bb70bf4a73d3435e67be2a95ec807472"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+1/METIS.v5.1.2.x86_64-w64-mingw32.tar.gz"
