[[METIS]]
arch = "i686"
git-tree-sha1 = "3ccd99d454d0dac61e01314adab99459bd89f4f9"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "26ed5e54a86a9a40b45d1182d98c34b9d62d31e6799d7e417a2ad35c56d4ff2e"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+1/METIS.v4.0.3.i686-linux-musl.tar.gz"
[[METIS]]
arch = "aarch64"
git-tree-sha1 = "f7c66d25f596cbd3665f277df1eef57495078cc0"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "410c72e059ef99eaa5c3f66c61b7ac97db39d9ab3c7a7b4de828dd1f5ed671fe"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+1/METIS.v4.0.3.aarch64-linux-musl.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "07b93f2925d2738deb239ed92cd169f6afb113cd"
os = "windows"

    [[METIS.download]]
    sha256 = "7cc92e11ec071818587ec4f1e52c738a0a57be71f28570baba8e85b7526c240f"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+1/METIS.v4.0.3.i686-w64-mingw32.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "9624c7016a8f636a4530a4677a79e851b3907725"
os = "windows"

    [[METIS.download]]
    sha256 = "7b8e2f567f79d00270d16a2e02b12246359adb6d885c0d468b269b5426a437d5"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+1/METIS.v4.0.3.x86_64-w64-mingw32.tar.gz"
[[METIS]]
arch = "armv7l"
git-tree-sha1 = "d0c6e7f4c3dcf82574b4a44af8010168c86551f2"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "836aacc45e171d3bff5eb95796a04f0897585a8d6ae364f06b1cbb6d936d0bce"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+1/METIS.v4.0.3.armv7l-linux-gnueabihf.tar.gz"
[[METIS]]
arch = "armv7l"
git-tree-sha1 = "39823ca40b0d723f49482d6ee9f5c0b711def5ef"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "b11e887b05271acaa761cc5486e91e52ea284cfc41a67d7c7416ea9f85a05ed1"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+1/METIS.v4.0.3.armv7l-linux-musleabihf.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "fdfda689bbdf5cb004680cf6a43197c7d24487ac"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "824408720c9a6829bf7e9a40387eb2a51028a81075d1c1d9e0be9b516ed5a2eb"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+1/METIS.v4.0.3.i686-linux-gnu.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "5273441b7c0c0d7c6cc7faa56eb1dc92acbb87f0"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "898830ea493d1168d887eaecdc1208c49eb47e688be51840e39927aa69bfc57c"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+1/METIS.v4.0.3.x86_64-linux-gnu.tar.gz"
[[METIS]]
arch = "powerpc64le"
git-tree-sha1 = "c99e78b3914effbb2434e799e3cb5b630eca5146"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "f93691b63830906a194781ffecc697a93d6f3c67c299882274155e1c45ffd731"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+1/METIS.v4.0.3.powerpc64le-linux-gnu.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "c8b848a5ed746fd5504be5d03c11498cc18f860e"
os = "macos"

    [[METIS.download]]
    sha256 = "98aa685c36eb62e0a4ff46a97b7ba074b7b730b0930dbb10bf89437d61e97777"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+1/METIS.v4.0.3.x86_64-apple-darwin14.tar.gz"
[[METIS]]
arch = "aarch64"
git-tree-sha1 = "360f7f7ac2dd8842e86cfeb19b040e15ca6ebd73"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "973601ee07d3183b4ff5298fb76727eda9147d52a32f9e01cb5916bbefe29efb"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+1/METIS.v4.0.3.aarch64-linux-gnu.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "46df7e621313b45d05eaf6adc64b3df02f4357e9"
os = "freebsd"

    [[METIS.download]]
    sha256 = "7691646d4a1d7c4b7a335bdafb7028963688712e69145165a747b7b0dfd6e8a6"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+1/METIS.v4.0.3.x86_64-unknown-freebsd11.1.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "755da52c95c1b52efc05b1bf2212f902f7e99b21"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "8b19d151876fc60758402ad701d68e52162127f40e22e370be5cb93411fb5e2c"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+1/METIS.v4.0.3.x86_64-linux-musl.tar.gz"
