[[METIS]]
arch = "i686"
git-tree-sha1 = "96d67e9ca6a6d77328ac4090d5cca090cdd647d8"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "64e1a4d6bd20a979af1f1201c3eb5825df8e23ca6bbe2a5b24ed66f736ecaaa4"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+1/METIS.v5.1.0.i686-linux-gnu.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "3df9adb22c1e3cdbb1ec1f20f626cee5580f12d8"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "4bebbcb0a6dc08f6b986d72f5d11d068317de770dbc1788a2a00de20d2d76f28"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+1/METIS.v5.1.0.i686-linux-musl.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "fed2bc6996d89a1ced7b409a4efd0bbf3789efb2"
os = "macos"

    [[METIS.download]]
    sha256 = "84234c422820081e4759f8e644768f52cd30bea67f1c7b807b9eee54147db34a"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+1/METIS.v5.1.0.x86_64-apple-darwin14.tar.gz"
[[METIS]]
arch = "powerpc64le"
git-tree-sha1 = "7b1b78c9b55bf0fc54c8c9f627c78ceee23a3d4a"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "e8576ba1bd9502db1cf95e24998da9bc71942914e7cf02df843d1ebd7a772b81"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+1/METIS.v5.1.0.powerpc64le-linux-gnu.tar.gz"
[[METIS]]
arch = "aarch64"
git-tree-sha1 = "7ac5a8b87e800cd4a39748e2b376abd1b87e43a6"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "7e3fa9fc1e53683e7c14accc049e62b18b712fae71b5a4d29e212a7bf8da9a52"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+1/METIS.v5.1.0.aarch64-linux-gnu.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "9db7d09de201aed256501d86299739e2a289ab40"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "18e1eecfd432da5fab3583922edfe82b7b8854fdf20cb47da951811827ac52e7"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+1/METIS.v5.1.0.x86_64-linux-musl.tar.gz"
[[METIS]]
arch = "aarch64"
git-tree-sha1 = "f149dab195684f29e66107ff34616852e2879fdf"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "95ac689b2f12ec84d6a708706c8ac002785e4467d0b848bd2c5e9f82db59ff55"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+1/METIS.v5.1.0.aarch64-linux-musl.tar.gz"
[[METIS]]
arch = "armv7l"
git-tree-sha1 = "c4c82cb053ee58d2e2d7f079514764247a608eb9"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "f343a7b714b32939bcc858d9a6072960c8036a532bc81a149db62011314d985d"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+1/METIS.v5.1.0.arm-linux-musleabihf.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "1b5785d4ead86706e0ff6dfb4ec8dfb6e227aaac"
os = "windows"

    [[METIS.download]]
    sha256 = "4d7113ce4cf7bf09041f822b63202bf120e0cf5794860a8ca2f2c0b04d4ad7ef"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+1/METIS.v5.1.0.i686-w64-mingw32.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "c1613091020569da225b8c83f4e1217b21696798"
os = "freebsd"

    [[METIS.download]]
    sha256 = "cb8c28b51d1f80b2f6bd026bfc256f65d4a568a0779f189cc8e8794085bab1a2"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+1/METIS.v5.1.0.x86_64-unknown-freebsd11.1.tar.gz"
[[METIS]]
arch = "armv7l"
git-tree-sha1 = "87edd3c20b904c3b5211b582efae662b71e147a9"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "6689d37634edb40a2d788f23e0744d6597d63797ac4a15fb54a6956e16fe6931"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+1/METIS.v5.1.0.arm-linux-gnueabihf.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "9427c26484a30d5e42a1b9e9e107436b99e37a5a"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "1a0caf4f2a2038cd080261dd63998ca0a7a59bc0df181d4ff0df8d2a9c1f15dc"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+1/METIS.v5.1.0.x86_64-linux-gnu.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "3bc52a8ecc2836c9a93eb0a83425d2cb3871b08b"
os = "windows"

    [[METIS.download]]
    sha256 = "dea7a009681a6ee059182dc8524cac49d1aa4dbbc6eadcdddf1bc9b6cc9d245a"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+1/METIS.v5.1.0.x86_64-w64-mingw32.tar.gz"
