[[METIS]]
arch = "aarch64"
git-tree-sha1 = "c448a73d12dd9005f5443d0a90dd44fcbec9dae2"
os = "macos"

    [[METIS.download]]
    sha256 = "b07cf73b22394d64790a9a347ea04d01eba2922353b08e25ff3103367a1b1c8f"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.3+0/METIS.v5.1.3.aarch64-apple-darwin.tar.gz"
[[METIS]]
arch = "aarch64"
git-tree-sha1 = "8681d61a6f371708ef6ed0a2b9deee5168da81f2"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "4ddab1ca88680b3c8f3b4f794da0dbe5ad9d11e73cb8f9cd966561ad5ddd3aaa"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.3+0/METIS.v5.1.3.aarch64-linux-gnu.tar.gz"
[[METIS]]
arch = "aarch64"
git-tree-sha1 = "cb0731b419b24d7b7be62bcaeff73484a098e4b0"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "086cf16f387d70a34e32da7890b08ac28420397b9d69c7c2c589449c6004108e"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.3+0/METIS.v5.1.3.aarch64-linux-musl.tar.gz"
[[METIS]]
arch = "aarch64"
git-tree-sha1 = "5045ed931705e49e3fd74179ceefc0dda7bcbd81"
os = "freebsd"

    [[METIS.download]]
    sha256 = "53be9adea7b584f9447ebfee3afbc0d0edf53e2b3e1b29249cb327ccdb807957"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.3+0/METIS.v5.1.3.aarch64-unknown-freebsd.tar.gz"
[[METIS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f1882547a0bb67822406b1ebd31fd425f2e87480"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "9008a534aadb20fa0b1ad1456603ceec56dcccf3198a6217f001b123db39da77"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.3+0/METIS.v5.1.3.armv6l-linux-gnueabihf.tar.gz"
[[METIS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f69512d4247ed05ce6d83d9397af268309c13612"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "0a20a8c96d8277cd73a03618c4f53e15899c0badc7ea7008024058e21f2d9446"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.3+0/METIS.v5.1.3.armv6l-linux-musleabihf.tar.gz"
[[METIS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7392b07981281468c32cb36cf6e94e4b742e3fdf"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "603fbc9658ff59923f19b0fc75c29063ae9920844116b5f0fa772058b1bca585"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.3+0/METIS.v5.1.3.armv7l-linux-gnueabihf.tar.gz"
[[METIS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f49949dbf5164bdb0c2c139904c9dea79f34aa5e"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "9c7f865d9e493e23e1b441fa2147ec5ec76ab6c81cdf09ee7752bcfc65401a18"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.3+0/METIS.v5.1.3.armv7l-linux-musleabihf.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "3a4618419c60a80ec245742b16caabc5fce9be2e"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "0dca527c5d8b54859571156649c2b7cf6c87211ea00a2b87b5be52e8bfe8e801"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.3+0/METIS.v5.1.3.i686-linux-gnu.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "bb6d9d1274b4de4d47d4b22b86c88358ce17cf0a"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "9db4ab8cf8409bbb8deb44d288371abbb82b46aedb3b898e392e54e3f2fe3ff8"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.3+0/METIS.v5.1.3.i686-linux-musl.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "7a7eac953bbd45042bc2414ca17e6bb757647cbc"
os = "windows"

    [[METIS.download]]
    sha256 = "87bebc13443929a1a12a8e79559d00c0150eed94f625497210dff9e794de375d"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.3+0/METIS.v5.1.3.i686-w64-mingw32.tar.gz"
[[METIS]]
arch = "powerpc64le"
git-tree-sha1 = "d4b2db64868237826d716d2ce12eefc0a2cddb81"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "92129cb261ac2d43b93a9f5685c2eb7ec3d30d6dbdc133e8f00a8f0e4f87a5e1"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.3+0/METIS.v5.1.3.powerpc64le-linux-gnu.tar.gz"
[[METIS]]
arch = "riscv64"
git-tree-sha1 = "3411c7497991d689ed99a09f8dfeaea1f14a8e55"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "cf3eba2f5da4356d112ba1305b7443accc4c130db7a1b7f4695ff8b46af24b1e"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.3+0/METIS.v5.1.3.riscv64-linux-gnu.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "57586d98cd0f674087135c9ac15133c069c6c3d5"
os = "macos"

    [[METIS.download]]
    sha256 = "be48485044665f4094b31398f0e7be6207db6e5aa169d871beda991318aaf3c2"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.3+0/METIS.v5.1.3.x86_64-apple-darwin.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "ca6d7039e1208e821d097fa0b6d1e57af4c165c7"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "baea64cdf82c4b779b1742abe2611a80762ce611a025ba3c72c2dc073357a726"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.3+0/METIS.v5.1.3.x86_64-linux-gnu.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "6e9998ea5f48f6a33d3555b038915abee09a31f2"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "0d686d42426e9363d1a0aef4c95e0f1e3be9f0a84fb51b5f5785066a15a99a7c"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.3+0/METIS.v5.1.3.x86_64-linux-musl.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "b8cc1ce6c1e00e6da1bea1595e8c5a58c00421b7"
os = "freebsd"

    [[METIS.download]]
    sha256 = "a35ea6f22ca8074b8ea42a1deff45de2558c22ff221310372501690cdf744852"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.3+0/METIS.v5.1.3.x86_64-unknown-freebsd.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "c06c0cd69177914a392d42284fea8125a5960a79"
os = "windows"

    [[METIS.download]]
    sha256 = "3d05ab210d3d48c94fd38d6171884b439f9c992864855fe158065822d2c05ce8"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.3+0/METIS.v5.1.3.x86_64-w64-mingw32.tar.gz"
