[[METIS]]
arch = "aarch64"
git-tree-sha1 = "92d05a42220fdd0b59536d0b9c60c5de428a630d"
os = "macos"

    [[METIS.download]]
    sha256 = "3978de780ce532d388a8c6cb2ab922a76dc2bc3e486f7f49f3b7f2978adc335b"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+0/METIS.v5.1.2.aarch64-apple-darwin.tar.gz"
[[METIS]]
arch = "aarch64"
git-tree-sha1 = "6702ccb4d0bbaf737125c7d579cb9856c919b0c6"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "066dcbdfac00af834ef119a621b287361434514b2941b5976dcc1fa243fd1670"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+0/METIS.v5.1.2.aarch64-linux-gnu.tar.gz"
[[METIS]]
arch = "aarch64"
git-tree-sha1 = "2952295ea079cd3ef81255c7a97bf19e1cb7bab9"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "b2e6c17138814f7ce74144b41a136a0b132e4fb75629e49e6875899e1edd0851"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+0/METIS.v5.1.2.aarch64-linux-musl.tar.gz"
[[METIS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d7dc41cd593b7ee3a0051e3a55a1a839fec1c18c"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "ecdc6cdd7c130d3b785cde4653fde22a9f54787d168bc54d74f1f06f3975afb7"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+0/METIS.v5.1.2.armv6l-linux-gnueabihf.tar.gz"
[[METIS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ae19efafea02bb914c11bfd59b5682ffebc2d97f"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "33559290ea746ea9e8f12c1be404fe2c0051e77268cbaba1b3631da41b362fca"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+0/METIS.v5.1.2.armv6l-linux-musleabihf.tar.gz"
[[METIS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a0b0bab39734c790bb3a14dafe362bbe75954b67"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "95d940d8a30ec99ea73745f72983c254a47160fb8161f787999680dfa5e07eb6"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+0/METIS.v5.1.2.armv7l-linux-gnueabihf.tar.gz"
[[METIS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0e0fb000b5fe3cba2a51d4074d74211b023228a0"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "86332a8e4487ce7330babc94b6164bd88da175304e7b08c34f81264116a60d3d"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+0/METIS.v5.1.2.armv7l-linux-musleabihf.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "9807c1aa229254b1b3064f65d377684582ae955e"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "5c4a6e440cde611d13ec8eaad268e667a5243e40f8c904125f9362cc1c5fe978"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+0/METIS.v5.1.2.i686-linux-gnu.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "844277398872bd0f2a05155030169748bdcc976f"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "48ef36ccf4a94cd426652d82595620a85cd4a4014fea9775a189cb79fd0a9b9e"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+0/METIS.v5.1.2.i686-linux-musl.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "b3052f7e3f5b75b7e061e2cbb3ceea21f88beac5"
os = "windows"

    [[METIS.download]]
    sha256 = "664c7b4ad2fd58c26d359f8d20ef4de719ab5fe2003d3fac1232c3f072dfcd37"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+0/METIS.v5.1.2.i686-w64-mingw32.tar.gz"
[[METIS]]
arch = "powerpc64le"
git-tree-sha1 = "7235eedb6b12bf77a52f115a717a8b0a49eaeea6"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "59410577f62a13d38aceb36cff0c300748e02014a28ec61d37092ef577634908"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+0/METIS.v5.1.2.powerpc64le-linux-gnu.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "085281efe66fd732117b891040ff6132937ea29b"
os = "macos"

    [[METIS.download]]
    sha256 = "fc6eaff09ad4f939e97dd8f46a8459208eeca581fe0f506c124ed02dc62a1867"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+0/METIS.v5.1.2.x86_64-apple-darwin.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "e5244f73466343373a87ed1345efac5e3440fa96"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "cd715cbf6a41fb7b56d6336de3699b355427cfbb334dc367c4afcae15fa209c7"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+0/METIS.v5.1.2.x86_64-linux-gnu.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "836adfc774a36d54d61ee11cac9621a243e3c927"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "29565174a3629c3ba39c313cf05aa083b542fec9922f99e641257ba699891648"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+0/METIS.v5.1.2.x86_64-linux-musl.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "d27d670c8aa300c92c0f039c131118259ac16d6d"
os = "freebsd"

    [[METIS.download]]
    sha256 = "ec93b77d4ee772ca9fedc3174401788b5d3c42e21b3589b93aad5f7040d4791f"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+0/METIS.v5.1.2.x86_64-unknown-freebsd.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "4edb4158850f5c8426a4a332ec2bc34737dcd222"
os = "windows"

    [[METIS.download]]
    sha256 = "0686f3c67b8e145d16c238a078a560e7c2e98fff46c6a072cb1b714fc806654c"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.2+0/METIS.v5.1.2.x86_64-w64-mingw32.tar.gz"
