[[METIS]]
arch = "aarch64"
git-tree-sha1 = "4a49e028dc9b09a26cfbba2f59a6186685d6f71b"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "f031286651d7c7791113d4846eef1664a0c614a4e18f1687cbc6e6388dce31a3"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+0/METIS.v4.0.3.aarch64-linux-musl.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "d664f42d1e65e3770056804a92e97f0419e05995"
os = "windows"

    [[METIS.download]]
    sha256 = "080fac7198f9691663e35508327f81303709f7170d065ad39086797972f3a845"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+0/METIS.v4.0.3.i686-w64-mingw32.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "dfa7f949106be3d16ce6d50d13cafdb0724780cd"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "6d05a4ec14a1e286b348075d220cbe88a04797a36c6524e68b01cdc387a8d376"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+0/METIS.v4.0.3.x86_64-linux-musl.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "7962c68c07746bef7bdb3a0d144486042f92e4a6"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "04f69b9c97a525430a2edf16078aba0af717dcd579b1c45b8e9f39842412d9d7"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+0/METIS.v4.0.3.i686-linux-gnu.tar.gz"
[[METIS]]
arch = "armv7l"
git-tree-sha1 = "05a75af6afeaea1af1fd8bceecd33abfbdfc49cc"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "f9b5fd5d7b56cf66337dc707e5e4982101b2376bc0f5ab73bc07f0f5b4509674"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+0/METIS.v4.0.3.armv7l-linux-gnueabihf.tar.gz"
[[METIS]]
arch = "aarch64"
git-tree-sha1 = "9f2517817b5bf7a61673537d8269c4c449026d7d"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "5b0c408d58f9ecdae427c95fcb5ac155c5b207916b6fbd1b85f3a4a27f6cb27d"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+0/METIS.v4.0.3.aarch64-linux-gnu.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "9f233c9c626cda07f2c075769778bb59cabecac0"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "19613ba0a121f874c2c688cfd09c020c41a998828de7c32c785483a9ed33067d"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+0/METIS.v4.0.3.x86_64-linux-gnu.tar.gz"
[[METIS]]
arch = "powerpc64le"
git-tree-sha1 = "bc01cacf3dc384a228ab05bb298438616858480b"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "f613c25fcb65f8fb7b74257d088f18f0faf636267da5a4a7ba0ebf47f1446fa2"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+0/METIS.v4.0.3.powerpc64le-linux-gnu.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "2b1fa41df4b964fff9cae187b4f04ec66c26c42d"
os = "macos"

    [[METIS.download]]
    sha256 = "e49668ea068b4ef4737b6dbc1562fe6fa6897967b859d5f5a0556afee3e7c62a"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+0/METIS.v4.0.3.x86_64-apple-darwin14.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "7c58a2e330cd92018a15d5feb76c652ef36cf994"
os = "freebsd"

    [[METIS.download]]
    sha256 = "91edb47074d6670823629c747f730d673df2a80149c77fc731c26ebe0ba20da9"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+0/METIS.v4.0.3.x86_64-unknown-freebsd11.1.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "cb6f775fb2cca88b6c7cbe9419f0f1e85e876d20"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "76e393eb0fc8bea6ce43331721efe42e83864ce5daccfde2302e284481907efc"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+0/METIS.v4.0.3.i686-linux-musl.tar.gz"
[[METIS]]
arch = "armv7l"
git-tree-sha1 = "41e25ba4fb1d740868558c2b7b2afec4f2d82a0c"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "fe80b95e0b340ef3651289a1478344f2aa2aa9ae3b51b4b1577c2d7c83362700"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+0/METIS.v4.0.3.armv7l-linux-musleabihf.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "4c7e6c1f510289b2f804684549f0afcbc421eaf0"
os = "windows"

    [[METIS.download]]
    sha256 = "6427b64bd9c277c2dcae53d0f7ba2a8d9dbc923fc50fc8492865545dffa5445a"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v4.0.3+0/METIS.v4.0.3.x86_64-w64-mingw32.tar.gz"
