[[METIS]]
arch = "i686"
git-tree-sha1 = "0f0a7bb6deecbb0536e9a7cbdb6c07e2ef740b78"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "d761812e467d064312dac660f1ba11d9ccf286f4423b2efe7612ecc702191b41"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+3/METIS.v5.1.0.i686-linux-musl.tar.gz"
[[METIS]]
arch = "aarch64"
git-tree-sha1 = "0bc99b1c675bff73a862667203b07facd6ecb35f"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "3b256a816609742498f082afd131b29ec9996d804b2d34a241a2dba57459718e"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+3/METIS.v5.1.0.aarch64-linux-musl.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "9ca87eaa3cae5f203f9e23b76397b199b298c5e5"
os = "windows"

    [[METIS.download]]
    sha256 = "67106f883642120928e3ebebb8273d706cc66ed76cc7c3446b7f4d0475be2837"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+3/METIS.v5.1.0.i686-w64-mingw32.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "eb1bdfe02cbd527256ec1da7989e7c049437ac81"
os = "windows"

    [[METIS.download]]
    sha256 = "196b135905387eb2f90a570272f7ee5ed4526bd13bf16322fb0418aeed615d89"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+3/METIS.v5.1.0.x86_64-w64-mingw32.tar.gz"
[[METIS]]
arch = "armv7l"
git-tree-sha1 = "585eb78a1982c0eacb938e619673f298472f1f93"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "1fcdbbd9f390537cd8c80459181ea0f1330f4a9aab2ae199a221e2e9b05fe32f"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+3/METIS.v5.1.0.armv7l-linux-gnueabihf.tar.gz"
[[METIS]]
arch = "armv7l"
git-tree-sha1 = "a99fc34be91273efe1ba383aea37d03ace160b3f"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "b795608b3de115d7385634b4f5cdf57a624a6e6efd90e8bbfcdcf08a9fa30341"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+3/METIS.v5.1.0.armv7l-linux-musleabihf.tar.gz"
[[METIS]]
arch = "i686"
git-tree-sha1 = "c3afe4487ef8cc9977cba406094a232930b63bd8"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "b04e2c1e87275ab9e809a311017f5c0691eafa0e8a31b4cef8513e13ce2ecf3e"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+3/METIS.v5.1.0.i686-linux-gnu.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "40fc026fa03a0f30667b2c5dc182e8c3040eeb14"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "2c807c477a0fa35878e6f44a7cb93349e19bc892ecc0b2a58d922202a7b7be9c"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+3/METIS.v5.1.0.x86_64-linux-gnu.tar.gz"
[[METIS]]
arch = "powerpc64le"
git-tree-sha1 = "a3c24dfa18e4f4c490d58daf24bf66493181d251"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "9814a76b4260278439d0f1eb60484be53fa004dff7482a5ce82b48c6b4f3f892"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+3/METIS.v5.1.0.powerpc64le-linux-gnu.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "3c464ec95048088c79cca067d6c10c8e4d9ca54f"
os = "macos"

    [[METIS.download]]
    sha256 = "267bfe76d1c5c818ee57e798701d54deb2a2fe58d4c5f8b55f3af5448661e0a2"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+3/METIS.v5.1.0.x86_64-apple-darwin14.tar.gz"
[[METIS]]
arch = "aarch64"
git-tree-sha1 = "08f21ad83d6b39b453268cce1627a7093f3bc3a6"
libc = "glibc"
os = "linux"

    [[METIS.download]]
    sha256 = "2ba1cdee9f53ef5db1802dda61a4c8cf118e90bf102a0740e06cc33006b6285e"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+3/METIS.v5.1.0.aarch64-linux-gnu.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "cd3d25b1a80e26aa6444c1f1493fedb8bc7355bf"
os = "freebsd"

    [[METIS.download]]
    sha256 = "41cba6e9112717f96895d56396adb17874c4d19d9c549b36567a52f7993f2846"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+3/METIS.v5.1.0.x86_64-unknown-freebsd11.1.tar.gz"
[[METIS]]
arch = "x86_64"
git-tree-sha1 = "1ef17c487c173a3374e64d41d3cf33da08bb2a99"
libc = "musl"
os = "linux"

    [[METIS.download]]
    sha256 = "0a29094a9a612f75053e856a4bd400945e1c62970a9f5b07bfa8114690158b48"
    url = "https://github.com/JuliaBinaryWrappers/METIS_jll.jl/releases/download/METIS-v5.1.0+3/METIS.v5.1.0.x86_64-linux-musl.tar.gz"
