# Autogenerated wrapper script for METIS_jll for i686-w64-mingw32
export libmetis, libmetis_Int32_Real64, libmetis_Int64_Real32, libmetis_Int64_Real64

JLLWrappers.@generate_wrapper_header("METIS")
JLLWrappers.@declare_library_product(libmetis, "libmetis.dll")
JLLWrappers.@declare_library_product(libmetis_Int32_Real64, "libmetis_Int32_Real64.dll")
JLLWrappers.@declare_library_product(libmetis_Int64_Real32, "libmetis_Int64_Real32.dll")
JLLWrappers.@declare_library_product(libmetis_Int64_Real64, "libmetis_Int64_Real64.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmetis,
        "bin\\libmetis.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmetis_Int32_Real64,
        "bin\\metis\\metis_Int32_Real64\\bin\\libmetis_Int32_Real64.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmetis_Int64_Real32,
        "bin\\metis\\metis_Int64_Real32\\bin\\libmetis_Int64_Real32.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmetis_Int64_Real64,
        "bin\\metis\\metis_Int64_Real64\\bin\\libmetis_Int64_Real64.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
