# Autogenerated wrapper script for METIS_jll for x86_64-apple-darwin
export libmetis, libmetis_Int32_Real64, libmetis_Int64_Real32, libmetis_Int64_Real64

JLLWrappers.@generate_wrapper_header("METIS")
JLLWrappers.@declare_library_product(libmetis, "@rpath/libmetis.dylib")
JLLWrappers.@declare_library_product(libmetis_Int32_Real64, "@rpath/libmetis_Int32_Real64.dylib")
JLLWrappers.@declare_library_product(libmetis_Int64_Real32, "@rpath/libmetis_Int64_Real32.dylib")
JLLWrappers.@declare_library_product(libmetis_Int64_Real64, "@rpath/libmetis_Int64_Real64.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmetis,
        "lib/libmetis.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmetis_Int32_Real64,
        "lib/metis/metis_Int32_Real64/lib/libmetis_Int32_Real64.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmetis_Int64_Real32,
        "lib/metis/metis_Int64_Real32/lib/libmetis_Int64_Real32.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmetis_Int64_Real64,
        "lib/metis/metis_Int64_Real64/lib/libmetis_Int64_Real64.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
